name: task_manager
description: "Task Manager App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  sqflite: ^2.3.3+1
  path: ^1.9.0
  connectivity_plus: ^6.0.3
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg